version: "3"
services:
  space-rocket-controller-variable-initialization:
    container_name: space-rocket-controller-variable-initialization
    build:
      context: .
    volumes:
      - .:/app
    environment:
#      - RABBITMQ_URL=amqp://guest:guest@localhost:5672/space
      - RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672/space
      - QUEUE_ORIGIN=space-rocket-controller-variable-initialization-queue
      - QUEUE_TO=space-rocket-controller-clc-motion-vectors-relative-to-ground-queue
